import {memo,useEffect,useMemo,useRef,useState} from 'react';
import * as ToggleGroup from 'radix-ui/toggle-group';
import {LayoutGrid,Type,File,Search,X,Copy,Check,Download,Inbox} from 'lucide-react';
import {IconButton,PlatformIcon} from './ui';
import {copyText} from './api';
const Row=memo(function Row({item,platform,name,notify}){
 const [copied,setCopied]=useState(false),timer=useRef();useEffect(()=>()=>clearTimeout(timer.current),[]);
 const file=Boolean(item.fileName||item.contentType?.startsWith('image/')),url='/api/download?id='+encodeURIComponent(item.id),image=item.contentType?.startsWith('image/');
 const date=new Date(item.createdAt);
 return <article className="history-row"><span title={name}><PlatformIcon platform={platform} name={name}/></span><div className="min-w-0 flex-1">{image?<img src={url} loading="lazy" alt={item.fileName||'Shared image'} className="image-preview"/>:<p className="item-text">{file?item.fileName:item.text}</p>}</div><time dateTime={date.toISOString()} title={date.toLocaleString()}>{date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false})}</time>{file?<a className="icon-button" href={url} download={item.fileName||'OmaSend-image'} aria-label={'Download '+(item.fileName||'image')} title="Download"><Download/></a>:<IconButton label={copied?'Copied':'Copy text'} onClick={async()=>{try{await copyText(item.text);setCopied(true);notify('Copied');clearTimeout(timer.current);timer.current=setTimeout(()=>setCopied(false),1600);}catch(e){notify(e.message);}}}>{copied?<Check className="confirm"/>:<Copy/>}</IconButton>}</article>;
});
export default memo(function History({items,devices,hostId,hostPlatform,hostName,notify}){
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[searching,setSearching]=useState(false);
 const visible=useMemo(()=>items.filter(item=>{const file=Boolean(item.fileName||item.contentType?.startsWith('image/'));return (filter==='all'||(filter==='files')===file)&&(!query||[item.text,item.fileName,item.originName].some(value=>value?.toLocaleLowerCase().includes(query.toLocaleLowerCase())));}),[items,filter,query]);
 return <section className="history" aria-labelledby="clipboard-title"><div className="history-toolbar"><h1 id="clipboard-title">Clipboard</h1><ToggleGroup.Root type="single" value={filter} onValueChange={value=>value&&setFilter(value)} className="filter-group" aria-label="History filter">{[['all',LayoutGrid,'All'],['text',Type,'Text'],['files',File,'Files']].map(([value,Icon,label])=><ToggleGroup.Item key={value} value={value} aria-label={label}><Icon/></ToggleGroup.Item>)}</ToggleGroup.Root><IconButton label={searching?'Close search':'Search'} onClick={()=>{setSearching(!searching);setQuery('');}}>{searching?<X/>:<Search/>}</IconButton></div>{searching&&<div className="search-field"><Search/><input autoFocus type="search" aria-label="Search history" placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)}/></div>}<div aria-label="Shared history">{visible.map(item=>{const device=devices.find(peer=>peer.id===item.originId);return <Row key={item.id} item={item} platform={item.isLocal||item.originId===hostId?hostPlatform:device?.platform} name={item.isLocal?hostName:item.originName} notify={notify}/>;})}{!visible.length&&<div className="empty" role="status" aria-label={items.length?'No matches':'Nothing shared yet'}><Inbox/></div>}</div></section>;
});
