import {useState} from 'react';
import * as Dialog from 'radix-ui/dialog';
import * as Switch from 'radix-ui/switch';
import {X,Sun,Moon,ChevronDown} from 'lucide-react';
import {IconButton} from './ui';
import {api} from './api';
export default function Settings({triggerRef,open,onOpenChange,state,refresh,notify,theme,setTheme}){
 const [trusted,setTrusted]=useState(state.status.trustedLAN),[key,setKey]=useState(''),[busy,setBusy]=useState(false);
 async function save(action){if(busy)return;setBusy(true);try{await action();await refresh();notify('Saved');}catch(e){notify(e.message);}finally{setBusy(false);}}
 return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content" onCloseAutoFocus={event=>{event.preventDefault();triggerRef.current?.focus();}}><div className="flex items-center justify-between"><Dialog.Title>Settings</Dialog.Title><Dialog.Close asChild><IconButton label="Close settings"><X/></IconButton></Dialog.Close></div><Dialog.Description className="sr-only">Appearance and device pairing</Dialog.Description>
 <div className="setting-row"><span>Appearance</span><div className="flex gap-1"><IconButton label="Light appearance" aria-pressed={theme==='light'} onClick={()=>setTheme('light')}><Sun/></IconButton><IconButton label="Dark appearance" aria-pressed={theme==='dark'} onClick={()=>setTheme('dark')}><Moon/></IconButton></div></div>
 <details className="advanced"><summary>Pairing<ChevronDown/></summary>{state.admin?<><form onSubmit={e=>{e.preventDefault();save(()=>api('settings',{trustedLAN:trusted}));}}><div className="setting-row"><label htmlFor="trusted">Trusted LAN</label><Switch.Root id="trusted" checked={trusted} onCheckedChange={setTrusted} className="switch"><Switch.Thumb className="switch-thumb"/></Switch.Root></div><p className="setting-note">Unencrypted. Anyone on this network can read or send items.</p><button className="save-button" disabled={busy||trusted===state.status.trustedLAN}>Save</button></form>{!state.status.trustedLAN&&<form className="pair-form" onSubmit={e=>{e.preventDefault();save(async()=>{await api('settings',{pairingCode:key.trim()});setKey('');});}}><label htmlFor="key">Pairing key</label><input id="key" type="password" autoComplete="off" placeholder="Paste key" value={key} onChange={e=>setKey(e.target.value)} minLength={20} maxLength={1024} required/><button className="save-button" disabled={busy}>Pair</button></form>}</>:<p className="setting-note">Pairing settings are available on the host’s localhost page.</p>}
 </details><details className="advanced"><summary>Manual connection<ChevronDown/></summary><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);save(()=>api('connect',{host:String(form.get('host')).trim(),port:Number(form.get('port'))}));}}><label htmlFor="host">IP address</label><input id="host" name="host" placeholder="192.168.1.20" required/><label htmlFor="port">Port</label><input id="port" name="port" type="number" min="1" max="65535" defaultValue="53317" required/><button className="save-button" disabled={busy}>Connect</button></form></details>
 </Dialog.Content></Dialog.Portal></Dialog.Root>;
}
